name: C/C++ CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install programs
      run: |
        sudo apt install -y libgtest-dev
        sudo apt install -y libsubunit-dev

    - name: Run GTest
      run: |
        cd src
        make tests
